export const rhythmPatterns = [
  {
    title: "A",
    pattern: "1000",
    temp: 80,
    note: "4n",
    level: "rhythm",
    id: 0,
  },
  {
    title: "B",
    pattern: "0100",
    temp: 80,
    note: "4n",
    level: "rhythm",
    id: 1,
  },
  {
    title: "C",
    pattern: "0010",
    temp: 80,
    note: "4n",
    level: "rhythm",
    id: 2,
  },
  {
    title: "D",
    pattern: "0001",
    temp: 80,
    note: "4n",
    level: "rhythm",
    id: 3,
  },
  {
    title: "E",
    pattern: "1100",
    temp: 80,
    note: "4n",
    level: "rhythm",
    id: 4,
  },
  {
    title: "F",
    pattern: "0110",
    temp: 80,
    note: "4n",
    level: "rhythm",
    id: 5,
  },
  {
    title: "G",
    pattern: "0011",
    temp: 80,
    note: "4n",
    level: "rhythm",
    id: 6,
  },
  {
    title: "H",
    pattern: "1001",
    temp: 80,
    note: "4n",
    level: "rhythm",
    id: 7,
  },
  {
    title: "I",
    pattern: "1010",
    temp: 80,
    note: "4n",
    level: "rhythm",
    id: 8,
  },
  {
    title: "J",
    pattern: "0101",
    temp: 80,
    note: "4n",
    level: "rhythm",
    id: 9,
  },
  {
    title: "K",
    pattern: "1110",
    temp: 80,
    note: "4n",
    level: "rhythm",
    id: 10,
  },
  {
    title: "L",
    pattern: "0111",
    temp: 80,
    note: "4n",
    level: "rhythm",
    id: 11
  },
  {
    title: "M",
    pattern: "1011",
    temp: 80,
    note: "4n",
    level: "rhythm",
    id: 12,
  },
  {
    title: "N",
    pattern: "1101",
    temp: 80,
    note: "4n",
    level: "rhythm",
    id: 13,
  },
  {
    title: "O",
    pattern: "1111",
    temp: 80,
    note: "4n",
    level: "rhythm",
    id: 14,
  },
  {
    title: "P",
    pattern: "0000",
    temp: 80,
    note: "4n",
    level: "rhythm",
    id: 15,
  },
  // {
  //   title: "Q",
  //   pattern: "100",
  //   temp: 80,
  //   note: "4n",
  //   level: "rhythm",
  //   position: 51,
  // },
  // {
  //   title: "R",
  //   pattern: "010",
  //   temp: 80,
  //   note: "4n",
  //   level: "rhythm",
  //   position: 52,
  // },
  // {
  //   title: "S",
  //   pattern: "001",
  //   temp: 80,
  //   note: "4n",
  //   level: "rhythm",
  //   position: 53,
  // },
  // {
  //   title: "T",
  //   pattern: "110",
  //   temp: 80,
  //   note: "4n",
  //   level: "rhythm",
  //   position: 54,
  // },
  // {
  //   title: "U",
  //   pattern: "011",
  //   temp: 80,
  //   note: "4n",
  //   level: "rhythm",
  //   position: 55,
  // },
  // {
  //   title: "V",
  //   pattern: "101",
  //   temp: 80,
  //   note: "4n",
  //   level: "rhythm",
  //   position: 56,
  // },
  // {
  //   title: "W",
  //   pattern: "111",
  //   temp: 80,
  //   note: "4n",
  //   level: "rhythm",
  //   position: 57,
  // },
  // {
  //   title: "X",
  //   pattern: "000",
  //   temp: 80,
  //   note: "4n",
  //   level: "rhythm",
  //   position: 57,
  // },
];
