export const rhythmPatterns = [
  {
    title: "A",
    pattern: "1000",
    temp: 80,
    note: "4n",
    level: "rhythm",
    position: 38,
  },
  {
    title: "B",
    pattern: "0100",
    temp: 80,
    note: "4n",
    level: "rhythm",
    position: 39,
  },
  {
    title: "C",
    pattern: "0010",
    temp: 80,
    note: "4n",
    level: "rhythm",
    position: 40,
  },
  {
    title: "D",
    pattern: "0001",
    temp: 80,
    note: "4n",
    level: "rhythm",
    position: 41,
  },
  {
    title: "E",
    pattern: "1100",
    temp: 80,
    note: "4n",
    level: "rhythm",
    position: 42,
  },
  {
    title: "F",
    pattern: "0110",
    temp: 80,
    note: "4n",
    level: "rhythm",
    position: 43,
  },
  {
    title: "G",
    pattern: "0011",
    temp: 80,
    note: "4n",
    level: "rhythm",
    position: 44,
  },
  {
    title: "H",
    pattern: "1001",
    temp: 80,
    note: "4n",
    level: "rhythm",
    position: 46,
  },
  {
    title: "I",
    pattern: "1010",
    temp: 80,
    note: "4n",
    level: "rhythm",
    position: 45,
  },
  {
    title: "J",
    pattern: "0101",
    temp: 80,
    note: "4n",
    level: "rhythm",
    position: 48,
  },
  {
    title: "K",
    pattern: "1110",
    temp: 80,
    note: "4n",
    level: "rhythm",
    position: 45,
  },
  {
    title: "L",
    pattern: "0111",
    temp: 80,
    note: "4n",
    level: "rhythm",
    position: 45,
  },
  {
    title: "M",
    pattern: "1011",
    temp: 80,
    note: "4n",
    level: "rhythm",
    position: 47,
  },
  {
    title: "N",
    pattern: "1101",
    temp: 80,
    note: "4n",
    level: "rhythm",
    position: 48,
  },
  {
    title: "O",
    pattern: "1111",
    temp: 80,
    note: "4n",
    level: "rhythm",
    position: 49,
  },
  {
    title: "P",
    pattern: "0000",
    temp: 80,
    note: "4n",
    level: "rhythm",
    position: 50,
  },
  // {
  //   title: "Q",
  //   pattern: "100",
  //   temp: 80,
  //   note: "4n",
  //   level: "rhythm",
  //   position: 51,
  // },
  // {
  //   title: "R",
  //   pattern: "010",
  //   temp: 80,
  //   note: "4n",
  //   level: "rhythm",
  //   position: 52,
  // },
  // {
  //   title: "S",
  //   pattern: "001",
  //   temp: 80,
  //   note: "4n",
  //   level: "rhythm",
  //   position: 53,
  // },
  // {
  //   title: "T",
  //   pattern: "110",
  //   temp: 80,
  //   note: "4n",
  //   level: "rhythm",
  //   position: 54,
  // },
  // {
  //   title: "U",
  //   pattern: "011",
  //   temp: 80,
  //   note: "4n",
  //   level: "rhythm",
  //   position: 55,
  // },
  // {
  //   title: "V",
  //   pattern: "101",
  //   temp: 80,
  //   note: "4n",
  //   level: "rhythm",
  //   position: 56,
  // },
  // {
  //   title: "W",
  //   pattern: "111",
  //   temp: 80,
  //   note: "4n",
  //   level: "rhythm",
  //   position: 57,
  // },
  // {
  //   title: "X",
  //   pattern: "000",
  //   temp: 80,
  //   note: "4n",
  //   level: "rhythm",
  //   position: 57,
  // },
];
